version: '3.8'

services:
  cake_pos_db:
    image: postgres:16-alpine
    container_name: cake_pos_db_container
    restart: unless-stopped
    env_file: [.env.dev]
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-user}
      POSTGRES_DB: ${POSTGRES_DB:-cake_pos_db}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - cake_pos_db_data:/var/lib/postgresql/data
      - ./backend/database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  cake_pos_db_data:
